---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../components/apps/rwn-optimizations
  # - ../../../components/apps/openshift-sriov-network-operator/overlays/default
  # - ../../../components/apps/openshift-ptp/overlays/default
